package.json
src/singleton.js
src/tracer.js

Changes the signature of `initNewTracer()` to take an tracer implementation object (rather than implicitly create a new one via the global tracer.  I believe this qualifies as a small, logical change as it makes two similar methods have similar signatures.
Note: the OpenTracing spec at this point specifies the `Tracer` interface but not how tracers are created / acquired; with that in mind, I believe this change fits with the standard.
(Also for what it's worth, the LightStep tracer allows multiple Tracer instances to be created, so this change was needed to support that functionality.)

Make initNewTracer() mirror initGlobalTracer()

---

src/constants.js
src/span.js
src/trace_context.js
src/tracer.js
webpack.config.js

Ensure the `API_CONFORMANCE_CHECKS` code blocks (i.e. check number and type of arguments on each call) exist only in debug.
Specifically, modifies the `webpack.config.js` configuration to set `API_CONFORMANCE_CHECKS` as a constant that will be removed by dead-code elimination step of the UglifyJS plugin. Note: I manually verified in the generated production and debug code that the checks will be done only in debug builds.
Resolves https://github.com/opentracing/opentracing-javascript/issues/7.

Run API conformance checks in debug only

---

.travis.yml
dist/.gitignore
package.json

Automates the JavaScript compilation step (i.e. running `webpack`) when publishing the OpenTracing NPM package.
The two changes are:
1. Include an empty `.npmignore` in the `dist` directory so the published package *does not* ignore the files in the `dist` directory. The default behavior of NPM is to use the `.gitignore` file if there is no `.npmignore` file, but in this case, the files in the published package and the files in the source are *not* supposed to be the same.
2. Add a `prepublish` "script" step that runs the `webpack` step to do the build. The `prepublish` script is automatically invoked on publish so that building the source is no longer a manual step.

Automate webpack to run as part of publish step

---

README.md
package.json
src/carriers/binary_carrier.js
src/carriers/split_text_carrier.js
src/constants.js
src/index.js
src/singleton.js
src/span.js
src/tracer.js
test/unittest.js

Gets the JavaScript code in sync with some of the more recent OpenTracing spec updates:
- Renames the `set/getTraceAttribute` APIs to `set/getBaggageItem`
- Adds the binary and split text carriers and `inject`/`join` APIs to `Tracer`
- Adds `setOperationName` to `Span` (not new to the spec, but was not in the JS code before)
- Return the `this` object by default on most `Span` methods without an explicit return value in case users want to chain calls (and more specifically, since that's the pattern Python seems to be doing and keeping the platform APIs similar seems like a good thing)
​

Sync to recent OpenTracing spec updates

---

package.json
src/span.js
src/tracer.js

Fixes a few small divergences from the common API:
* Removes `startChildSpan` from `Span`
* Fix two references to `TraceAttributes` that should have been `Baggage`
* Allow `startSpan(operationName, { parent : parent})` as a call signature

API conformance

---

package.json
src/span.js
src/tracer.js

Two more small changes after further testing:
* Fix a few places where `FORMAT_BINARY` was written instead of `FORMAT_SPLIT_BINARY`
* Use `RegExp.test()` not `RegExp.match()`

Fix FORMAT_SPLIT_BINARY

---

src/singleton.js
webpack.config.js

Removes an accidental "double initialization" when setting the global tracer. Rather than using the passed-in object directly, it was cloning the passed in object via a call to `newTracer`.  This "worked" so wasn't noticed before, but is obviously inefficient!
Also, this changes the webpack config to use "umd" format (rather than "var" format) for the browser for broader compatibility.  The "var" format makes assumptions about accessibility of global variables that may not be true in different JS module systems.

Remove double Tracer implementation initialization

---

src/binary_carrier.js
src/constants.js
src/singleton.js
src/tracer.js
test/unittest.js

Resolves https://github.com/opentracing/opentracing-javascript/issues/22 by updating the semantics of the `carrier` for `FORMAT_BINARY`.
In short, `carrier` was previously specified as being an `ArrayBuffer` - but in JavaScript those are fixed length buffers, which creates some usage complications.  The specification is now "loosened" to be any valid object with a `buffer` field - which in turn can any array-like type (e.g. ArrayBuffer, Array, Uint8Array, Float32Array, etc.)

Update FORMAT_BINARY carrier format

---

src/default_tracer.js

Fixes a defect where the singleton was not properly shared when the library consumer was including OpenTracing, for example, both via a `<script>` tag and an implicit copy via webpack or browserify.
The code simply incorrect before as it never set the shared singleton value.

Handle the case of <script> and webpack

---

src/singleton.js
test/unittest.js

Allow `let tracer = OpenTracing.initNewTracer(null)` to be a valid way to get a no-op tracer instance.
* Fix a defect where the code assumed a non-null value for e tracer
* Add a unit test to ensure passing null creates a valid no-op tracer
Note: the majority of the diffs are cosmetic indentation changes to the unit tests.

Add conditionals to allow a null implementation object

---

esdoc.json
src/singleton.js
src/span.js
src/tracer.js

Updates the code comments to use [ESDoc](https://esdoc.org/) format comments and adds a `esdoc.json` config file. This allows static HTML API documentation to be generated from the code.

Add support for ESDoc API documentation

---

package.json

Fixes #36 . 
**TL;DR**: roll back the version of eslint to 2.13.1 to avoid the version mismatch complaints (and since no eslint 3.x features are needed)
The TravisCI builds were failing due to a version requirement of the eslint base config (`eslint-config-airbnb`). This is a bit of a false negative since newer version of eslint works with the base config. In any case, this all seems to be related to https://github.com/airbnb/javascript/issues/936, which is currently still open.

Roll back eslint version

---

CHANGELOG.rst
src/reference.js

(Consistent with Go and this morning's https://github.com/opentracing/opentracing-python/commit/924093dc8da36e6e8ae63ac9bd9f41c523e21e64#diff-a1898244c8c6ea29725a1d5333973b9aR130)

Use the referee nomenclature

---

README.md
src/tracer.js

Adds the missing `childOf` method to Tracer. This was introduced in the transition to the `SpanContext`-based API.

Add the missing childOf method to Tracer

---

src/singleton.js
src/tracer.js

Moves `followsFrom` from `Singleton` to `Tracer`.
A bit more detail: I was a bit hasty in addressing the the missing method in the last PR. The `followsFrom` method also needs to be moved. In the case of a single global tracer, having `childOf` and `followsFrom` on the `Singleton` object works, but it does not work for the cases of multiple `Tracer` objects (since they're not methods of `Tracer` and `Tracer.startSpan` refers to them as instance methods). The only methods `Singleton` should be adding to `Tracer` are the global initialization methods.
*An aside on Singleton*
The `Singleton` currently exists solely for the convenience of:
```js
let globalTracer = require('opentracing');  // Both the global instance & free functions
```
vs
```js
let opentracing = require('opentracing');   // …
```

Move followsFrom from Singleton to Tracer.

---

src/span.js

The operation name length test was incorrect. It was checking that all operation names are zero length not that they are greater than zero length.

Fix inverted operation name length test

---

README.md

Hi there,
Thanks for this great project, I am excited to use it. I have found a little typo I wanted to fix real quick 👍 
Thanks for your patience!

Fix typo in compatibility snippet

---

CHANGELOG.rst
src/global_tracer.ts
src/test/opentracing_api.ts

The global tracer delegate uses the delegate as the this context when
calling the configured global tracer. This will break many tracing
implementations. Most notably, this will break all tracing
implementations which subclass the opentracing provided Tracer class.

global tracer call delegation uses wrong this

---

README.md

The default export in opentracing/lib/test/api_compatibility.js. is a property on the exports object and thus is accessed with `.default`.
There can be only one default property on the exports object. 
This property does not therefore need to be destructured.

Fix how requiring apiCompatibilityChecks

---

src/constants.ts

http://opentracing.io/spec/ returns a 404. This commit switches the broken link with a link to the github specification repo.

Fixed Broken URL

---

.gitignore
src/index.ts
src/mock_tracer/mock_tracer.ts
src/test/opentracing_api.ts

Fixes https://github.com/opentracing/opentracing-javascript/issues/93
The `SpanOptions` type is not exported from the module. This change simply adds an export to the `index.ts` file

expose span options

---

README.md

few grammatical bugs are fixed and license information is added. 
#99

Fix grammatical errors and add Licence information

---

package-lock.json
package.json

This PR downgrades the typescript package version to `2.7.x` to avoid a bug that's currently in `2.8.x`. This is temporary so we can cut a new release. We can upgrade back to the `2.8.x` track once the bug in typescript is fixed.

Downgrade typescript version to avoid build error

---

package-lock.json
package.json
src/mock_tracer/mock_report.ts
src/mock_tracer/mock_span.ts

This PR removes the dependency on `lodash` since it was causing dependency problems for depending libraries. It was also only used for functionalities that are readily available in pure JS. This problem existed as well when `underscore` was used instead of `lodash` (#75).
Fixes #95

remove dependency on lodash

---

LICENSE
package.json

(All CNCF projects should use the Apache License 2.0 - see opentracing/specification#61 for context.)
- Please correct me if I'm wrong, but it seems like the original intent was to license OT-JavaScript as Apache 2.0, anyway (as mentioned in the [README](https://github.com/opentracing/opentracing-javascript#license)).
- However, the [LICENSE file](https://github.com/opentracing/opentracing-javascript/blob/master/LICENSE) itself contains the text for the MIT License, and a copyright reference to `2016 Resonance Labs, Inc`.
- In any case, GitHub currently detects the OT-JavaScript license as MIT, not Apache 2.0.
- Could someone clarify the reason for referencing the Apache license in `README` and using the MIT license in the `LICENSE` file?
If this commit really does represent a switch from …

edit OT-JS license info so that GitHub recognizes it

---

src/mock_tracer/mock_context.ts

There seems to be a legitimate circular dependency here that causes problems when I build this library using Snowpack:
1. ./index.ts imports ./mock_tracer/index.ts
2. ./mock_tracer/index.ts imports ./mock_tracer/mock_tracer.ts
3. ./mock_tracer/mock_tracer.ts imports ./mock_tracer/mock_context.ts
4. ./mock_tracer/mock_context.ts imports ./index.ts
I _think_ it should be fixed by simply importing `SpanContext` directly rather than importing the full ./index.ts.

Fix circular dependency in mock_context
